## Registry image
## ref: https://hub.docker.com/_/registry/
##
image: registry.devopsedu.com:5000/devops/registry

## Registry image version
## ref: https://hub.docker.com/_/registry/tags/
##
imageTag: "2.6.2"

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

httpPort: 5000
logLevel: "info"
authTokenRealm: "https://gitlab.devopsedu.com/jwt/auth"
authTokenService: "container_registry"
authTokenIssuer: "gitlab-issuer"
storageDeleteEnabled: "true"

ingress:
  enabled: false

  ## Registry Ingress annotations
  ##
  # annotations:
  #  kubernetes.io/ingress.class: nginx
  #  kubernetes.io/tls-acme: 'true'

  ## Registry Ingress hostnames
  ## Must be provided if Ingress is enabled
  ##
  # hosts:
  #  - gitlab.devopsedu.com

  # secretName: gitlab-server-tls


## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  ## Registry requires a good deal of resources. We have split out Postgres and
  ## redis, which helps some. Refer to the guidelines for larger installs.
  ## ref: https://docs.gitlab.com/ce/install/requirements.html#hardware-requirements
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 500m

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
## ref: https://docs.gitlab.com/ce/install/requirements.html#storage
##
persistence:
  ## This volume persists generated configuration files, keys, and certs.
  ##
  enabled: true
  size: 10Gi
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass: ""
  accessMode: ReadWriteOnce
