apiVersion: v1
description: Distributed object storage server built for cloud applications and devops.
home: https://minio.io
icon: https://www.minio.io/logo/img/logo-dark.svg
keywords:
- storage
- object-storage
- S3
maintainers:
- email: hello@acale.ph
  name: Acaleph
- email: hello@minio.io
  name: Minio
name: minio
sources:
- https://github.com/minio/minio
version: 0.1.0
