name: jenkins
home: https://jenkins.io/
version: 0.16.1
appVersion: 2.107
description: Open source continuous integration server. It supports multiple SCM tools
  including CVS, Subversion and Git. It can execute Apache Ant and Apache Maven-based
  projects as well as arbitrary scripts.
sources:
- https://github.com/jenkinsci/jenkins
- https://github.com/jenkinsci/docker-jnlp-slave
maintainers:
- name: dinnawin
  email: dinnawin@easyops.cn
icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
