dependencies:
- name: redis
  version: 0.7.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: postgresql
  version: 0.6.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: minio
  version: 0.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: runner
  version: 0.4.1
  repository: http://charts.lwolf.org/
  condition: runner.enabled
- name: registry
  version: 0.2.0
  repository: http://charts.lwolf.org/
  condition: registry.enabled
